<?php

/**
 * @file
 * Contains editorial_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function editorial_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the editorial_content module.
    case 'help.page.editorial_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function editorial_content_theme() {
  $theme = [];
  $theme['editorial_content'] = [
    'render element' => 'elements',
    'file' => 'editorial_content.page.inc',
    'template' => 'editorial_content',
  ];
  $theme['editorial_content_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'editorial_content.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 *
 * @todo change underscores to hyphens.
 */
function editorial_content_theme_suggestions_editorial_content(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#editorial_content'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'editorial_content__' . $sanitized_view_mode;
  $suggestions[] = 'editorial_content__' . $entity->bundle();
  $suggestions[] = 'editorial_content__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'editorial_content__' . $entity->id();
  $suggestions[] = 'editorial_content__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}


///**
// * Implements hook_entity_type_alter().
// */
//function editorial_content_entity_type_alter(array &$entity_types) {
//  if (isset($entity_types['editorial_content_type'])) {
//    if (!$entity_types['editorial_content_type']->getHandlerClass('form')) {
//      $entity_types['editorial_content_type']->setHandlerClass('form', [
//        'default' => 'Drupal\editorial_content\Form\EditorialContentTypeForm',
//        'add' => 'Drupal\editorial_content\Form\EditorialContentTypeForm',
//        'edit' => 'Drupal\editorial_content\Form\EditorialContentTypeForm',
//        'delete' => 'Drupal\editorial_content\Form\EditorialContentTypeDeleteForm'
//      ]);
//    }
//    if (!$entity_types['editorial_content_type']->getHandlerClass('route_provider')) {
//      $entity_types['editorial_content_type']->setHandlerClass('route_provider', [
//        'html' => 'Drupal\editorial_content\EditorialContentTypeHtmlRouteProvider',
//      ]);
//    }
//  }
//}

/**
 * Implements hook_form_alter().
 */
function editorial_content_form_alter(&$form, $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-editorial--page-1') {
    $form['created']['#type'] = 'date';
    $form['created_1']['#type'] = 'date';
    $form['changed']['#type'] = 'date';
    $form['changed_1']['#type'] = 'date';
  }
}
