module:
  ab_testing: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  affiliate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  broker_page: 0
  c171: 0
  captcha: 0
  child: 0
  child_manager: 0
  child_sponsorship: 0
  ckeditor: 0
  company: 0
  config: 0
  config_translation: 0
  config_update: 0
  config_update_ui: 0
  contextual: 0
  country: 0
  country_manager: 0
  country_page: 0
  csv_serialization: 0
  ctools: 0
  datasourcehandler: 0
  datetime: 0
  devel: 0
  dropguard: 0
  dynamic_page_cache: 0
  editor: 0
  editorial: 0
  editorial_content: 0
  editorialfield: 0
  entity_reference_revisions: 0
  entity_test: 0
  field: 0
  field_collection: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_plus: 0
  filter: 0
  forms_suite: 0
  forms_survey: 0
  fs_affiliate_bridge: 0
  fs_datasource_bridge: 0
  fs_inxmail_bridge: 0
  fs_payment: 0
  fs_payment_payone: 0
  giftshop: 0
  gnode: 0
  google_tag_manager: 0
  group: 0
  help: 0
  hook_event_dispatcher: 0
  image: 0
  imagemagick: 0
  inline_entity_form: 0
  inxmail: 0
  ivision: 0
  ivision_nav16: 0
  joboffers: 0
  language: 0
  layout_plugin: 0
  link: 0
  locale: 0
  mailsystem: 0
  map: 0
  maxlength: 0
  memcache: 0
  menu_breadcrumb: 0
  menu_ui: 0
  metatag: 0
  metatag_access: 0
  metatag_open_graph: 0
  napkyn_tracking: 0
  news_article: 0
  node: 0
  obelix_contacts: 0
  obelix_main: 0
  offcanvas: 0
  options: 0
  page_cache: 0
  path: 0
  payment_gateway: 0
  payone: 0
  project: 0
  project_manager: 0
  public_donor: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  replicate: 0
  responsive_image: 0
  runningeventdonation: 0
  search: 0
  serialization: 0
  simple_sitemap: 0
  social_share: 0
  styled_image: 0
  swiftmailer: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  transition_page: 0
  transparency_bar: 0
  user: 0
  view_unpublished: 0
  views: 0
  views_ui: 0
  wovi_base: 0
  wv_de_site: 0
  wv_site: 0
  wv_tools: 0
  menu_link_content: 1
  pathauto: 1
  paragraphs: 11
theme:
  bootstrap: 0
  stable: 0
  beaufix: 0
  classy: 0
  seven: 0
  wovide: 0
  adminimal_theme: 0
  wvbasetheme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: de
profile: standard
