schemas:
  bootstrap: 8000
  wvbasetheme: 8000
_core:
  default_config_hash: 1uFogeFphl0Hg6oVCacZZ8mM_0wMZ7PS_RrmLbK5tf0
favicon:
  mimetype: image/vnd.microsoft.icon
  path: themes/worldvision/beaufix/favicon.ico
  url: 'http://worldvision.de/themes/worldvision/wvbasetheme/favicon.ico'
  use_default: false
cdn_jsdelivr_version: 3.3.6
region_wells:
  top_navigation: ''
  search: ''
  navigation: ''
  secondary_navigation: ''
  breadcrumbs: ''
  controls: ''
  content: ''
  footer_top_1: ''
  footer_top_2: ''
  footer_top_3: ''
  footer: ''
  footer_bottom_1: ''
  footer_bottom_2: ''
  footer_bottom_3: ''
logo:
  path: themes/worldvision/wvbasetheme/assets/images/logos/logo-de.jpg
  url: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
table: ''
langcode: de
