<?php

/**
 * @file
 * Contains affiliate.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function affiliate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the affiliate module.
    case 'help.page.affiliate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function affiliate_theme() {
  $theme = [];
  $theme['affiliate'] = [
    'render element' => 'elements',
    'file' => 'affiliate.page.inc',
    'template' => 'affiliate',
  ];
  $theme['affiliate_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'affiliate.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function affiliate_theme_suggestions_affiliate(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#affiliate'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'affiliate__' . $sanitized_view_mode;
  $suggestions[] = 'affiliate__' . $entity->bundle();
  $suggestions[] = 'affiliate__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'affiliate__' . $entity->id();
  $suggestions[] = 'affiliate__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
