<?php

/**
 * @file
 * Contains ivision_nav16.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ivision_nav16_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the ivision_nav16 module.
        case 'help.page.ivision_nav16':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Enables the iVision NAV 16 API') . '</p>';
            return $output;

        default:
    }
}
