<?php

/**
 * @file
 * Contains project.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function project_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the project module.
    case 'help.page.project':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles a World Vision Project') . '</p>';
      return $output;

    default:
  }
}
