wv_simma_connector.settings:
  type: config_object
  label: 'Simma Connector Settings'
  mapping:
    export:
      type: multiple
    migrate:
      type: config_object

wv_simma_connector.external_schemas:
  type: config_object
