<?php

/**
 * @file
 * Contains ffw_child_list_management.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ffw_child_list_management_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ffw_child_list_management module.
    case 'help.page.ffw_child_list_management':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module name is enough self explanatory.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ffw_child_list_management_theme() {
  return [
    'ffw_child_list_management' => [
      'render element' => 'children',
    ],
  ];
}
