<?php

/**
 * @file
 * Contains country_manager.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function country_manager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the country_manager module.
    case 'help.page.country_manager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extend the Country Module functionality') . '</p>';
      return $output;

    default:
  }
}
