display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          label: Titel
          separator: ', '
        type:
          label: 'Content type'
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        dropbutton:
          label: Operationen
      filters:
        status:
          expose:
            label: 'Published status'
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        type:
          expose:
            label: Typ
      empty:
        area_text_custom:
          content: 'No content available.'
      arguments:
        gid:
          exception:
            title: Alle
      title: Beiträge
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Beiträge
