<?php

/**
 * @file
 * Module defined hooks API.
 */

/**
 * Used to alter children gender options on all forms which is generated by child controller.
 *
 * @param array $options
 * @param array $original_options
 */
function hook_child_gender_options_alter(array &$options, array $original_options) {
  // Delete all not original keys.
  foreach (array_keys(array_diff_key($options, $original_options)) as $key) {
    unset($options[$key]);
  }
}
